# permissions for end users to view deploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deploy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo-operator
    app.kubernetes.io/part-of: demo-operator
    app.kubernetes.io/managed-by: kustomize
  name: deploy-viewer-role
rules:
- apiGroups:
  - demo.wsp.com
  resources:
  - deploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.wsp.com
  resources:
  - deploys/status
  verbs:
  - get
